CiteSeer:
  alpha: 0.2
  epochs: 500
  lr: 0.001
  p1: 0.8
  rate: 0.2
  label: 0
  layer: 2
  t: 0.3
Cora:
  epochs: 1000
  lr: 0.005
  p1: 0.5
  p2: 0.5
  rate: 0.3
  label: 0
  t: 0.3
  layer: 2
Com:
  alpha: 0.7
  epochs: 5000
  lr: 0.001
  p1: 0.8
  rate: 0.5
  t: 0.2
  label: 1
  layer: 1
Photo:
  alpha: 1
  epochs: 5000
  lr: 0.001
  p1: 0.8
  rate: 0.5
  t: 0.2
  label: 1
  layer: 1
Phy:
  alpha: 0.7
  epochs: 400
  lr: 0.001
  p1: 0.8
  rate: 0.1
  t: 0.2
  label: 1
  layer: 1
PubMed:
  alpha: 0.7
  epochs: 1000
  lr: 0.005
  p1: 0.8
  rate: 0.1
  t: 0.2
  label: 0
  layer: 2
CS:
  alpha: 0.7
  epochs: 10000
  lr: 0.005
  p1: 0.8
  rate: 0.3
  t: 0.2
  label: 1
  layer: 1
WikiCS:
  alpha: 0.7
  epochs: 200
  lr: 0.001
  p1: 0.5
  rate: 0.3
  t: 0.1
  label: 0
  layer: 2
arxiv:
  alpha: 0.4
  epochs: 3000
  lr: 0.005
  p1: 0.5
  rate: 0.15
  t: 0.2
  label: 0
  hidden: 256
  layer: 3
DBLP:
  alpha: 0.4
  epochs: 3000
  lr: 0.005
  p1: 0.5
  rate: 0.15
  t: 0.2
  label: 1
  hidden: 256
  layer: 3