MUTAG:
  out_hidden: 64
  hidden: 32
  epochs: 100
  lr: 1e-3
  rate: 0.3
  warmup: 100
  w: 1e-5
  acc: 89.88+-6.4
  alpha: 0.3
  layer: 1
  t: 0.3
PROTEINS:
  out_hidden: 32
  hidden: 32
  epochs: 50
  lr: 1e-3
  rate: 0.3
  warmup: 100
  w: 1e-5
  acc: 75.7+-3.65
  alpha: 0.5
  layer: 2
  t: 0.1
COLLAB:
  out_hidden: 32
  hidden: 32
  epochs: 400
  lr: 1e-3
  rate: 0.2
  warmup: 100
  w: 1e-5
  acc: 81.48+-1.35
  alpha: 0.1
  layer: 2
  t: 0.1
NCI1:
  out_hidden: 64
  hidden: 32
  epochs: 50
  lr: 1e-5
  rate: 0.1
  warmup: 100
  w: 1e-4
  acc: 80.58+-1.96
  alpha: 0.1
  layer: 3
  t: 0.1
IMDB-BINARY:
  out_hidden: 32
  hidden: 32
  epochs: 300
  lr: 1e-4
  rate: 0.1
  warmup: 100
  w: 5e-4
  acc: 76.0+-4.1
  alpha: 0.2
  layer: 2
  t: 0.1
IMDB-MULTI:
  out_hidden: 64
  hidden: 32
  epochs: 700
  lr: 1e-4
  rate: 0.4
  warmup: 100
  w: 1e-5
  acc: 52.53+-2.9
  alpha: 0.5
  layer: 2
  t: 0.1
REDDIT-BINARY:
  out_hidden: 64
  hidden: 32
  epochs: 600
  lr: 1e-3
  rate: 0.5
  warmup: 100
  w: 1e-5
  acc: 90.5+-2
  alpha: 0.5
  layer: 1
  t: 0.1
DD:
  out_hidden: 64
  hidden: 32
  epochs: 200
  lr: 1e-5
  rate: 0.2
  warmup: 100
  w: 1e-5
  acc: 79.53+-4.625
  alpha: 0.2
  layer: 2
  t: 0.1
NCI109:
  out_hidden: 64
  hidden: 32
  epochs: 50
  lr: 1e-5
  rate: 0.2
  warmup: 100
  w: 1e-5
  acc: 79.72+-1.6
  alpha: 0.1
  layer: 3
  t: 0.1
PTC_MR:
  out_hidden: 64
  hidden: 32
  epochs: 50
  lr: 1e-5
  rate: 0.4
  warmup: 100
  w: 1e-5
  acc: 65.39+-1.6
  alpha: 0.3
  layer: 2
  t: 0.1
ENZYMES:
  out_hidden: 64
  hidden: 32
  epochs: 50
  lr: 1e-4
  rate: 0.4
  warmup: 100
  w: 1e-5
  acc: 57.83+-5.3
  alpha: 0.3
  layer: 2
  t: 0.1
REDDIT-MULTI-5K:
  out_hidden: 64
  hidden: 32
  epochs: 500
  lr: 1e-3
  rate: 0.5
  warmup: 100
  w: 1e-5
  acc: 90.5+-2
  alpha: 0.5
  layer: 1
  t: 0.1
MSRC_21:
  out_hidden: 64
  hidden: 32
  epochs: 500
  lr: 1e-3
  rate: 0.5
  warmup: 100
  w: 1e-5
  acc: 90.5+-2
  alpha: 0.5
  layer: 1
  t: 0.1